# Configuración general del proyecto StockPrep

# Carpeta de salida donde se copiarán imágenes renombradas y resultados
ruta_salida: output/

# Formato de exportación predeterminado
# Opciones válidas: JSON, CSV, XML
formato_salida: JSON

# ¿Se debe generar un archivo .txt con el resumen por imagen?
exportar_txt: true

# Configuración del modelo (Florence-2)
modelo:
  nombre: Florence-2-large
  tipo: safetensors
  # Ruta a la carpeta que contiene los pesos y configuraciones de Florence‑2
  ruta_local: models/Florence-2-large-ft-safetensors
  dtype: float32
  # ⚠️ NO TOCAR: esta opción evita fallos críticos al cargar Florence‑2 en Windows. Solo se usa flash_attn en Linux.
  flash_attn_enabled: false  # Florence2 requiere flash_attn solo en Linux. Desactivado explícitamente en model_manager.py

