# Configuración general del proyecto StockPrep

# Carpeta de salida donde se copiarán imágenes renombradas y resultados
ruta_salida: E:/Proyectos/StockPrep/salida

# Formato de exportación predeterminado
# Opciones válidas: JSON, CSV, XML
formato_salida: JSON

# ¿Se debe generar un archivo .txt con el resumen por imagen?
exportar_txt: true

# Configuración del modelo (Florence-2)
modelo:
  nombre: Florence-2-large
  tipo: safetensors
  ruta_local: modelos/Florence-2-large.safetensors
  dtype: float32
