from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from PIL import Image


GENERATOR_PATTERNS = [
    ("Google AI / Imagen", ("made with google ai", "google ai", "imagen ai", "imagen 3", "imagen 4")),
    ("Midjourney", ("midjourney",)),
    ("Leonardo AI", ("leonardo", "leonardo_phoenix", "leonardo diffusion")),
    ("Dreamina", ("dreamina",)),
    ("Freepik", ("freepik",)),
    ("Magnific", ("magnific",)),
    ("OpenAI / DALL-E", ("dall-e", "dalle", "openai", "chatgpt")),
    ("Adobe Firefly", ("adobe firefly", "firefly")),
    ("Stable Diffusion", ("stable diffusion", "automatic1111", "a1111", "comfyui", "civitai")),
    ("Flux", ("flux", "black forest labs", "bfl")),
    ("Ideogram", ("ideogram",)),
    ("PixVerse", ("pixverse",)),
    ("Runway", ("runway",)),
    ("Kling", ("kling",)),
]

AI_SIGNAL_PATTERNS = (
    "trainedalgorithmicmedia",
    "digital source type",
    "digitalsourcetype",
    "ai generated",
    "generated by ai",
    "generated with ai",
    "synthetic media",
    "c2pa",
)


def _flatten(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, (str, int, float, bool)):
        return str(value)
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="ignore")
    if isinstance(value, dict):
        return " ".join(f"{_flatten(k)} {_flatten(v)}" for k, v in value.items())
    if isinstance(value, (list, tuple, set)):
        return " ".join(_flatten(item) for item in value)
    return str(value)


def _read_embedded_text(image_path: Path, max_bytes: int = 5_000_000) -> str:
    parts = []
    try:
        with Image.open(image_path) as img:
            parts.append(_flatten(img.info))
    except Exception:
        pass

    try:
        data = image_path.read_bytes()
        if len(data) > max_bytes:
            data = data[: max_bytes // 2] + data[-max_bytes // 2 :]
        parts.append(data.decode("utf-8", errors="ignore"))
        parts.append(data.decode("latin-1", errors="ignore"))
    except Exception:
        pass

    return " ".join(parts)


def detect_ai_origin(
    image_path: str | Path | None = None,
    metadata: Any = None,
    original_name: str | None = None,
) -> dict[str, Any]:
    """Detect likely image generation origin from filename and embedded metadata."""
    signals = []
    sources = []

    if original_name:
        sources.append(original_name)

    if metadata:
        sources.append(_flatten(metadata))

    path = Path(image_path) if image_path else None
    if path and path.exists():
        sources.append(path.name)
        sources.append(_read_embedded_text(path))

    haystack = " ".join(sources).lower()
    haystack = re.sub(r"[_\-]+", " ", haystack)

    generator = None
    for label, patterns in GENERATOR_PATTERNS:
        for pattern in patterns:
            if pattern in haystack:
                generator = label
                signals.append(pattern)
                break
        if generator:
            break

    for pattern in AI_SIGNAL_PATTERNS:
        if pattern in haystack:
            signals.append(pattern)

    return {
        "is_ai_generated": bool(generator or signals),
        "generator": generator or "Desconocido",
        "signals": sorted(set(signals)),
        "source_name": original_name or (path.name if path else None),
    }


def metadata_with_ai_origin(metadata: dict[str, Any], image_path: str | Path, original_name: str | None = None) -> dict[str, Any]:
    updated = dict(metadata or {})
    updated["ai_origin"] = detect_ai_origin(image_path=image_path, metadata=updated, original_name=original_name)
    return updated
